# Generated by Django 5.2.4 on 2025-12-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_time',
            new_name='time',
        ),
    ]
